### ISSUE TITLE
Fetch certificate chain to local file

### ISSUE THREAD

**Issue by awakecoding** [robjtede/inspect-cert-chain#56]
Add the option to fetch the certificate chain to be saved to a local file instead of just displaying it. The most basic option should be a .pem file with the chain exactly in the order it was sent over the wire during the TLS handshake, without chain auto-completion - the goal here is to diagnose issues resulting from TLS servers configured with incomplete certificate chains, or certificate chains in the wrong order

**Comment by robjtede** [comment]
released in https://github.com/robjtede/inspect-cert-chain/releases/tag/v0.0.11
